# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                      Playbook for PACEMAKER config of HANA                  |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# TODO: Playbook not yet written
#       This is a placeholder 
#       This should probably be two playbooks:
#       1) HSR Configuration
#       2) PACEMAKER Config

- hosts:          "{{ sap_sid|upper }}_DB"                                           # TODO: Replace this with new inventory group; Change to correct group

  name:           PACEMAKER - HANA
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8
  
  - set_fact:
      tier:                                      [ ha, fencing ]
      primary_instance_name:                     "{{ ansible_play_hosts_all[0] }}"         # Setting up Primary Instance Name
      secondary_instance_name:                   "{{ ansible_play_hosts_all[1] }}"         # Setting up Secondary Instance Name
      sap_hana_fencing_spn_client_id:            "{{ hostvars.localhost.sap_fencing_spn_client_id }}"
      sap_hana_fencing_spn_client_pwd:           "{{ hostvars.localhost.sap_fencing_spn_pwd }}"
      sap_hana_fencing_spn_tenant_id:            "{{ hostvars.localhost.sap_fencing_spn_tenant_id }}"
    tags:
      - always

  - block:
      - include_role:
          name:     roles-sap/5.5-hanadb-pacemaker
    tags:
      - 5.5-hanadb-pacemaker



...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
